Mss 911 fix notifications kicker
guardian/mobile-notifications-content pull request #25
Opened 2019-09-27 13:13 UTC by NathanielBennett

Fixes the kicker bug
Makes the title of notification an optional string. 
Needs to be released at the same time as <n10n link coming>

2019-09-27 14:13 UTC, alexduf commented
If I may suggest the release procedure:

1. [ ] Merge the n10n PR, let it build but block deployment
1. [ ] Throttle the mobile-notification-content lambda in order to retain all outgoing notifications
1. [ ] Deploy the n10n PR
1. [ ] Deploy mobile-notification-content lambda
1. [ ] Un-throttle the lambda

_in theory_ that means no notification is sent during deployment, and the lambda should catch up by processing any missed event on the kinesis stream.

2019-09-27 14:14 UTC, NathanielBennett commented
Yes that's a good plan. I'll do it on Monday Morning, though

2019-09-27 15:35 UTC, alexduf requested changes

2019-09-27 15:35 UTC, alexduf commented on src/main/scala/com/gu/mobile/content/notifications/lib/ContentAlertPayloadBuilder.scala
> +      ""
It looks like you made the title optional but you're still returning an empty string here. Should that be returning None instead?

2019-09-27 15:35 UTC, alexduf commented on src/test/scala/com/gu/mobile/content/notifications/lib/ContentAlertPayloadBuilderSpec.scala
> +      val expectedMinutePayload = expectedPayloadForItem.copy(title = Some(""), topic = List(topic))
```suggestion
      val expectedMinutePayload = expectedPayloadForItem.copy(title = None, topic = List(topic))
```

2019-09-27 15:35 UTC, alexduf commented on src/test/scala/com/gu/mobile/content/notifications/lib/ContentAlertPayloadBuilderSpec.scala
> +      val expectedMinutePayload = expectedPayloadForItem.copy(title = Some(""), topic = List(topic))
```suggestion
      val expectedMinutePayload = expectedPayloadForItem.copy(title = None, topic = List(topic))
```

2019-09-27 15:35 UTC, alexduf commented on src/test/scala/com/gu/mobile/content/notifications/lib/ContentAlertPayloadBuilderSpec.scala
> +      val expectedPayload = expectedPayloadForItem.copy(title = Some(""), topic = List(topic))
```suggestion
      val expectedPayload = expectedPayloadForItem.copy(title = None, topic = List(topic))
```

2019-09-27 15:35 UTC, alexduf commented on src/test/scala/com/gu/mobile/content/notifications/lib/ContentAlertPayloadBuilderSpec.scala
> +      val expectedMinutePayload = expectedPayloadForItem.copy(title = Some(""), topic = List(briefingTopic))
```suggestion
      val expectedMinutePayload = expectedPayloadForItem.copy(title = None, topic = List(briefingTopic))
```

2019-09-30 09:50 UTC, alexduf approved these changes
I think it looks good

2019-09-30 10:45 UTC, merged